services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SATIS_USERNAME: ${SATIS_USERNAME:-}
        SATIS_PASSWORD: ${SATIS_PASSWORD:-}
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - .:/var/www/html
